         .: ..........:.                                                   
          ..:         :              _____.                                     
         _:____      _:___ __________)    |___      ______     ______        
    _____\_   /______\_  /_\  _     /\   ____/______\_   /_____\_   /_     
    \    _/  / /    __/   /   \____/ ¯   \     /     /    /    _/  / /              
    /____\_____\____\|____\_____\ _____________\__________\____\_____\       
     -nM$!:           :                                                        
          :         ..:..          [÷] RAPTOR / SECTOR 5 [÷]                                                         
         .:.........::: :                                                                   
          ·         :...:.. .
                        :                                           
  .......................                                                     
 .:angelwings·boobba·black dragon·blaze·   for realy slow, but friendship
 :celic·chriz·ctp·crusader·daytona·dvize   swapping time you may contact:
 :·guma·exon·fiction·ice·jacobs·kestrel· .........................                                      
 :kostek·madbart·marc·nemesis·norby·vega : raptor of sector5     :        ...:
 :·splatterhead·strife·tonid·vega·sharp· : konopnickiej 28       :        :
 :receiveer·thefounder·xtd·ziutek·zoltan : 17100 bielsk podlaski :........:
 ········································· poland

  email box: raptor2@free.polbox.pl        foreginers and ascii makers only...
