{203            TECHNICAL TEST:

{000        Colour 00
{001        Colour 01
{002        Colour 02
{003        Colour 03
{004        Colour 04
{005        Colour 05
{006        Colour 06
{007        Colour 07
{008        Colour 08
{009        Colour 09
{010        Colour 10
{011        Colour 11
{012        Colour 12
{013        Colour 13
{014        Colour 14

 {006C{000o{008l{000o{006r{000f{008u{000l {010d{003e{010s{009i{010g{003n{010!{009!{010!

{000Font0 (8x8)
{100Font1 (8x8)
{200Font2 (8x8)
{300Font3 (16x16)
{400Font4 (16x16)
{500Font5 (8x8)
{600Font6 (24x24)
{700Font7 (24x24)
{800Font8 (24x24){000


Notice that there are 9 fonts.


If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!

If you write max 38 columns  the  text
will  be draw  in 2 columns, like now!




Well, but is also possible to write a max of 78 columns, in full page,  and to
hevitate the 2 columns routine you have to exceed  the  38th column at the end
of the page, so ShowTime will understand that is not the  case to draw another
column:













This is the last line, so EXCEED the 38th column to hevitate the 2nd column!
All is clear now? You can made articles with 2 columns or 1 only, or mixted!
but... offcourse is not needed to write every last page line 39+ lines long,
you can use simply invisible spaces, like now:









The last line seems short, but there are much invisible spaces!






This is last line.                                         
Ok, is all for now!  But remember that
spaces placed over the 38th line in  a
2 column article  can  cause BUGS!! So
check every  time if  there are spaces
over the 38th column!!

Signed: Randy/Ram Jam
}
