



 »SML:»CL1:What happened to the DESIGN of »CL4:demos?»CL1:
     What happened to »CL4:demo music?»CL1:
 What happened to anything but a load
 of more or less »CL4:impressive routines»CL1:
        and an »CL4:endscroller???»CL1:

        And what happened to:
              »CL5:Diskmags?
                Packs?
             Musicdisks?
             Slideshows?»CL1:


              In short:


      »CL4:»BIG:   What happened to
                     the scene???»CL1:»SML:
»CL6:--------------------------------------
          »CL2:by Curt Cool/Depth
»CL6:--------------------------------------

»CL0:  This article contains some
observations of what has happened to
the »CL9:AMIGA Scene» in the last few years,
and some (boring?) analysis of WHY the
heck it is this way?!?). And maybe
even a thought of where the scene is
going these days. (oh, am I a scene
prophet??? NO?!?)...

              »BIG:»CL4:Demos:»SML:»CL0:
»CL2:Then:»CL0:
In 1992/93 and some of '94 most of the
demos which were considered cool
contained design. Maybe there was even
some overall idea or thought behind,
and they seemed very well thought out
altogether. Just watch demos like
»CL9:Desert Dream», »CL9:ARTE», »CL9:Interference», »CL9:Full
Moon», all »CL9:Andromeda» productions, some
»CL9:Melon» productions and lots and lots of
other nice, big or small, productions
with maybe humour, maybe just a well
thought out and well scheduled design,
or maybe something else that makes you
want to watch the demo or intro again.
»CL6:What happened to those???»CL0:
  Also, there were some more original
routines, and if you watch some old
demos on your trusty A500, you will
find some routines which deserves to
be updated to todays standard
(although there were also a lot of
vectors then...). 

»CL3:Now:»CL0: 
(»CL1:subtitled: why no design now?»)
Todays tendencies of no design and a
lot of routines just thrown in with no
structure or design at all except for
maybe the occasional picture or 
pop-art-style-comment (a la »CL9:Melons
"Planet M"», which started a new epoch
of design style which unfortunately
became boring after
"»CL9:Deep - The Psicolybin» (or whatever)
 »CL9:remix» (by »CL9:Parallax»)".
But most of todays winning
productions contain »CL6:NO DESIGN AT ALL.»CL0:
I don't if that is because we, the
sceners, suddenly prefer to watch the
same quite flickery bumpmapped,
texturemapped, gouraud-shaded,
phong-shaded, vectors featuring almost
the same objects and a black
background (or if we get really
advanced, maybe even pastel green, or
to reach the limit, with a pattern of
some sort with BOTH pastel green AND
red colours).
»CL5:Why is this? »CL0:Aren't everyone tired of
such lack of design?
Anyhow, it seems this lack of design
descends from the platform we all love
to hate, the PC, and so does those
vectors, so why do the scene keep
doing those productions? Of course,
vectors are nice, but not if they just
look the same all the time.
»CL5:Anyhow»CL0:, this no-design tendency
started at »CL9:THE PARTY 4» with demos by
»CL9:Virtual Dreams» (a sad goodbye for
»CL9:Dr. Skull»!?), »CL9:Oxyron» and some others,
and it's not strange that they did not
win. Just routines and no design
(unlike »CL9:NEXUS 7»).
Today, in 1996, it seems that the
scene is now once again beginning to
concern about design in demos, (and it
seems that those who cares about this
also wins the competitions, just look
at »CL9:3 Little Elks» or »CL9:The Black Lotus»),
but still, the most impressively coded
AMIGA demo of all time, »CL9:The Gate» by 
»CL9:Artwork», is just another proof of my
uppersit (»CL8:opposite!! -ed»CL0:) statement.

              »BIG:»CL4:Music:»SML:»CL4:
»CL2:Then:»CL0:
What has happened to demo & intro
music? In the old days demo music was
usually some sort of melodic
discotune, maybe even timed to the
routines and GFX to make the demo seem
very much as a whole instead (Desert
Dream is by far the best example). And
then again, who does not remember
legendary demo music like
»CL9:Audiomonsters» music for »CL9:Melons
"S.O.S." demo» or the brilliant music
in all the »CL9:Sanity», »CL9:Andromeda», »CL9:Anarchy»,
»CL9:Lemon.», (this list could go on 
forever) productions. Of course many
productions also contained techno
music then, but a higher percentage
of that techno was actually any good.
Also, back then, most 40k intros
contained some funny little melodic
chiptune, or maybe just some small
funky tune. Of course not all of it
was brilliant or even good, but still,
there was a generally higher quality
than now in 40ks as well...


»CL3:Now:»CL0:
Today, in 1996, we are on our way out
of a demo techno nightmare in demo
music. Although most of the really
major productions contains some quite
decent techno music, it still does not
reach the quality of the old days.
Still, not everything is bad, and the
music in the »CL9:CNCD» and »CL9:Parallax»
productions by »CL9:Groo», »CL9:Legend & Yolk» is
certainly both very original and
suitable for a demo.
But many productions still suffer,
look at »CL9:Artworks "Phi"» 40k intro, and
think about how it would have been
even better with some other tune
instead of the tune it features now...
Luckily the musical side of demos has
not suffered as badly as the design,
but still...

           »CL4:Why is all this?
       And where does it show?»CL0:

The reasons for the aforementioned
lacks could be:
»CL1:The deadline phenomenon:»CL0:
Coder wants to finish demo before the
deadline, no time to fit design in the
demo.
Also, it seems that most the
graphicians no longer want to do the
design, and so the coder ends up doing
the whole lot himself. Maybe some
groups do no longer work as groups,
more like a bunch of people, who uses
eachothers creations, again without
the structure.
Maybe it is the 90's phenomenon (in
real life as well), the bigger
selfishness which has been mentioned
in many medias and magazines outside
the scene as well.
To put it in some other words, maybe
the groups who does those demos
without design and fitting music do
not talk together as much as they
maybe ought to?
This could be the fault of the lower
amount of AMIGAs around those days,
after all, at the time of 1992/93
there was lots and lots of AMIGAs
around, in fact there were always lots
of other A500 owners to talk to quite
near to wherever you lived. And so
many groups started among friends...
But at the time when A1200 came out
some people (the sceners and a few
others) bought the new machine,
whereas the old user base, the ones
who had used A500 as a gamemachine,
almost quit using A500 within a year
or so, and bought PC's or other 
gamemachines of some sort.
So now the basis of a group with
members living really close to
eachother had become somewhat less
likely, and so the scene had to
restructure, and maybe that is the
period that we might now finally be at
an end of, since many sceners now have
modems and internet, and thereby we
are able to communicate with eachother
in a fast and reliable way which the
snail mail hardly is.
Some other reasons for the crappy
design could be the PC-demos which
usually doesn't possess any design
either, and then some AMIGA coders
have been inspired. Now, personally I
don't own a PC and have hardly ever
seen a PC demo, but that is just the
word on the street...

            »BIG:»CL4:Diskmags:»SML:»CL2:
Then:»CL0:
There were lots of them around, most
of them only reached a 1st issue, and
the hardworking article writers wrote
a lot about the sceners then, and
especially about the old legends and
possible new scene stars.
In the UK most diskmags were not very
scene-orientated.
Most diskmags had big delays.

»CL3:Now:»CL0:
Diskmags are at about the same
position as back then, new editors
have entered the scene (the days of
»CL9:Lord Helmet» and »CL9:Wolfman» have long
gone?!). But maybe some mags tend to
live on other peoples merits, so to
speak, with a few too many articles
about the old legends and almost no
words about the ones who will take
over. It's a bit depressing to read
about that and this scene-legend has
finally left the scene all the time,
and there are still new sceners to
come... :)
The UK mags haven't changed much
either although we haven't seen much
of »CL9:Grapevine» lately...

            »BIG:»CL4:Slideshows:»SML:»CL4:
»CL2:Then & Now:»CL0:
You see one of those occasionally and
usually they are quite good. I guess
that is all there is to write...

            »BIG:»CL4:Musicdisks:»SML:
»CL2:Then:»CL0:
Lots of musicdisks were made, usually
with a couple of small star & vector
routines and some nice graphics. It
was in 1991/92/93/94 »CL9:Crystal
Symphonies I/II», »CL9:Dizzy Tunes 1/2»,
»CL9:Spring Melodies», »CL9:Scoopex Melodies»,
»CL9:Memorial Songs», »CL9:Brunos Music Box III»,
and many many other cool musicdisks
saw the day of light. Everyone
remember those musicdisks as being
the best, and if you look in the
musicdisk charts in THIS chart, you
will still find them there... 

»CL3:Now:»CL0:
...which is because NO really
fantastic musicdisks has been released
since then. Instead people release a
lot of chip packs, and now some people
have also started to release
musicpacks, of which »CL9:SOUND» is the best
example. (»CL8::-( -ed») I'm not saying that
no musicdisks have been released, but
there are not really that many worth
remembering, simply due to the fact
that a musicdisk these days contains
no routines at all (no fun to watch),
just some design and a menu. I think
there are lots of musicians out there
who deserves to get their stuff
released on a decent musicdisk, so why
don't any of you sceners start working
on one?!?

               »BIG:»CL4:Packs:»SML:
»CL2:Then:»CL0:
In 1992/93/94 there were many packs
around, hosted by famous swappers
(well, they were famous in the
swapping scene...), and they were the
forum where you could find all the
great intros that were released just
for fun by many many groups.

»CL3:Now:»CL0:
Today, there are almost NO packs
outside Poland. There are a few
packmags, but they are not released
very often, and they are no longer the
forum for intros they used to be.  
This is because of two things: Groups
tend only to work on a production for
a party instead of spreading the
production on your average Sunday
afternoon, and so there is no matreial
to put on the packdisks. And besides
many productions fill so many
kilobytes that there isn't room on the
disk for neither the production NOR
the menu. Also, swapping has got
somewhat out of fashion although
modemtrading is SOOOOO boring, whereas
swapping is funny and friendly. A pity
there are so few packs... »CL6:BRING THEM
BACK I SAY!»...

              »BIG:»CL4:Status:»SML:»CL0:

The AMIGA scene is not nearly as big
as it has been, but there is still
lots of life in it. If »CL9:PIOS», »CL9:VisCorp»,
»CL9:Eagle» and »CL9:Phase 5» manage to make some
new AMIGAs with RISC processors of
some sort, we could really be in for a
treat, and with some luck, the AMIGA
will rise like a Phoenix above the
ashes and rule the computer world, and
most importantly, »CL9:THE SCENE», as it has
been doing for so many years now.

            »CL2:»BIG:VIVA »CL9:AMIGA!

          »CL2:VIVA»CL9: THE AMIGA SCENE!»CL0:»SML:

(pc is the fucking worst machine ever
        made... »CL9:KILL »CL5:BILL G.»CL0:)
              (»CL8:UGH! -ed»)

