»CL9:»SML:--------------------------------------
           »CL8:»BIG:The Scene Dying?
»CL9:»SML:--------------------------------------

»CL6:             by Curt Cool

»CL0:This seems to have been the subject of
many articles, wise words and so on in
the diskmag scene for a while now. And
of course, there is a good reason for
that since the scene IS dying.
Dying as well as I am dying, if I
follow the statistics I will be dead
in a little more than 50 years from
now - though with my present way of
life I suppose I won't live that long.
Anyhow, the above paragraphs were
written to show you that a phenomenon
like the scene does not die just like
that - »CL1:the scene is not dead until the
last scener leaves, the last demo is
released, and the last article
written.» So I presume that the scene
will more or less live for the next
approx. 15 years. Of course it will
become smaller and smaller but it will
take that much time before it
eventually disappears.

If you look at the Amiga scene in
comparison to other scenes, »CL1:the c64
scene» is a lot smaller, but definitely
still alive, and »CL5:the pc scene» is much,
much, much bigger, but then again
there's a lot of people there who just
play games and get the latest cracks -
the demos lack the design and
groundbreaking effects that the early
amiga demos featured - just the fancy
vectorroutine often does the trick,
simply because that classic demo-
effects are not impressive at all at a
»CL1:200Mhz Pentium Pro.»
On the Amiga Scene we have the
»CL9:c2p-hell,» and most of todays Amiga
demos certainly lack something
indefinable, something new, basically.
I guess that those of us who were on
the scene back in »CL1:'92-'93» and those
who were there even before became too
used to seeing new effects, to seeing
the work of the pioneers who managed
to squeal something impressive out of
our old slow »CL1:A500 with 0.5Mb FakeFast»
expansions of the cheapest kind. 
»PIC:Shade2.iff»




»CL4:But where is the scene going? Where
are the sceners going?
»CL6:Many an Amiga scener has converted to
the pc. »CL4:Or what?» So far, the trend of
Amiga groups who left for the pc scene
is to release one or two demos, and
then leave. At least the persons
responsible for the demos.
On the Amiga scene it seems as
»CL4:everybody is starting to code these
days» whereas many groups miss
graphicians? Why is that? 
As we can all see, the demos haven't
developed that much in the originality
stakes during the last, let's say 2
years. Everything has got somewhat
faster, due to optimizing, and most
certainly also due to rising system
limits. Basically, today everyone
needs at least an accelerated »CL4:A1200
with 8 megabytes» of memory to watch
the latest demos, and my meagre
configuration with »CL4:only 4 megs »is
certainly not able to show all the
demos released these days.
But the point to this is that it has
become easier to become a coder, since
the routines haven't developed much so
that everyone who has the time and
motivation to code can actually learn,
perhaps borrowing a c2p from eg. Scout
»CL4:(which I think is the c2p around which
is mostly used)». Of course it is
easier to find motivation for coding
if you can make the same routines as
eg. todays no. 1 scene heroes, »CL4:TBL».
The reasons why pixel graphicians are
harder to find than they used to be is
that today many graphicians use eg.
»CL4:photoshop» on pc to manipulate some

  »PIC:Shade4.iff»


















pictures, and so, some of the
uniqueness disappear, it becomes
easier to cheat, the motivation for
the graphician who used to sit in
front of good old »CL4:DPaint» all day long
disappears. Basically many graphicians
and musicians of today draw and
compose on pc, the graphicians using
»CL4:Photoshop», »CL4:Painter» and some other
programs which I do not know much
about, not being a graphician, and not
having a pc. The musicians are
composing in »CL4:FastTracker», thereby
having the option of making
multichannel mods as well, and I think
that I can safely say that maybe »CL4:25%»
of todays scene musicians are using
the pc for composing 4ch mods.


»CL0:So the times are changing, but a death
of the scene lies yet some years in
the future.
