/****************************************************************
   This file was created automatically by `FlexCat 2.4'
   from "commodities.cd".

   Do NOT edit by hand!
****************************************************************/

#ifndef commodities_H
#define commodities_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif


#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif

/***************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_CANT_OPEN_LIB 0
#define MSG_CANT_LOCK_SCR 1
#define MSG_CANT_GET_VI 2
#define MSG_CANT_CREATE_GADGET 3
#define MSG_CANT_CREATE_MENUS 4
#define MSG_CANT_LAYOUT_MENUS 5
#define MSG_CANT_CREATE_WIN 6
#define MSG_CANT_ALLOCATE_MEM 7
#define MSG_CANT_CREATE_MSGPORT 8
#define MSG_CANT_CREATE_BROKER 9
#define MSG_CANT_CREATE_CUSTOM 10
#define MSG_OK 11
#define MSG_MEN_PROJECT 12
#define MSG_MEN_PROJECT_QUIT 13
#define MSG_EXCHANGE_CXNAME 14
#define MSG_EXCHANGE_CXTITLE 15
#define MSG_EXCHANGE_CXDESCR 16
#define MSG_EXCHANGE_WINTITLE 17
#define MSG_EXCHANGE_LISTVIEW 18
#define MSG_EXCHANGE_INFO 19
#define MSG_EXCHANGE_GAD_SHOW 20
#define MSG_EXCHANGE_GAD_HIDE 21
#define MSG_EXCHANGE_GAD_REMOVE 22
#define MSG_EXCHANGE_CYCLE_ACTIVE 23
#define MSG_EXCHANGE_CYCLE_INACTIVE 24
#define MSG_BLANKER_CXNAME 25
#define MSG_BLANKER_CXTITLE 26
#define MSG_BLANKER_CXDESCR 27
#define MSG_CLICK2FNT_CXNAME 28
#define MSG_CLICK2FNT_CXTITLE 29
#define MSG_CLICK2FNT_CXDESCR 30
#define MSG_OPAQUE_CXNAME 31
#define MSG_OPAQUE_CXTITLE 32
#define MSG_OPAQUE_CXDESCR 33
#define MSG_AUTOPOINT_CXNAME 34
#define MSG_AUTOPOINT_CXTITLE 35
#define MSG_AUTOPOINT_CXDESCR 36
#define MSG_STARTMENU_CXNAME 37
#define MSG_STARTMENU_CXTITLE 38
#define MSG_STARTMENU_CXDESCR 39
#define MSG_FKEY_CXNAME 40
#define MSG_FKEY_CXTITLE 41
#define MSG_FKEY_CXDESCR 42
#define MSG_FKEY_WINTITLE 43
#define MSG_FKEY_DEFINED_KEYS 44
#define MSG_FKEY_NEW_KEY 45
#define MSG_FKEY_DELETE_KEY 46
#define MSG_FKEY_COMMAND 47
#define MSG_FKEY_COMMAND_PARAMS 48
#define MSG_FKEY_CMD_CYCLE_WIN 49
#define MSG_FKEY_CMD_CYCLE_SCR 50
#define MSG_FKEY_CMD_ENLARGE_WIN 51
#define MSG_FKEY_CMD_SHRINK_WIN 52
#define MSG_FKEY_CMD_TOGGLE_WIN_SIZE 53
#define MSG_FKEY_CMD_INSERT_TEXT 54
#define MSG_FKEY_CMD_RUN_PROG 55
#define MSG_FKEY_CMD_RUN_AREXX 56
#define MSG_FKEY_MEN_PROJECT 57
#define MSG_FKEY_MEN_PROJECT_SAVE 58
#define MSG_FKEY_MEN_PROJECT_HIDE 59
#define MSG_FKEY_MEN_PROJECT_ICONIFY 60
#define MSG_FKEY_MEN_PROJECT_QUIT 61
#define MSG_NOCAPSLOCK_CXNAME 62
#define MSG_NOCAPSLOCK_CXTITLE 63
#define MSG_NOCAPSLOCK_CXDESCR 64

#endif /* CATCOMP_NUMBERS */


/***************************************************************/

#ifdef CATCOMP_STRINGS

#define MSG_CANT_OPEN_LIB_STR "Can't open %s V%ld!\n"
#define MSG_CANT_LOCK_SCR_STR "Can't lock public screen!\n"
#define MSG_CANT_GET_VI_STR "Can't get VisualInfo!\n"
#define MSG_CANT_CREATE_GADGET_STR "Can't create gadgets!\n"
#define MSG_CANT_CREATE_MENUS_STR "Can't create menus!\n"
#define MSG_CANT_LAYOUT_MENUS_STR "Can't layout menus!\n"
#define MSG_CANT_CREATE_WIN_STR "Can't create window!\n"
#define MSG_CANT_ALLOCATE_MEM_STR "Can't allocate application memory!\n"
#define MSG_CANT_CREATE_MSGPORT_STR "Can't create message port!\n"
#define MSG_CANT_CREATE_BROKER_STR "Can't create CxBroker object!\n"
#define MSG_CANT_CREATE_CUSTOM_STR "Can't create CxCustom object!\n"
#define MSG_OK_STR "Ok"
#define MSG_MEN_PROJECT_STR "Project"
#define MSG_MEN_PROJECT_QUIT_STR "Q\000Quit"
#define MSG_EXCHANGE_CXNAME_STR "Exchange"
#define MSG_EXCHANGE_CXTITLE_STR "Commodities Exchange"
#define MSG_EXCHANGE_CXDESCR_STR "Controls system commodities"
#define MSG_EXCHANGE_WINTITLE_STR "Exchange"
#define MSG_EXCHANGE_LISTVIEW_STR "Available commodities"
#define MSG_EXCHANGE_INFO_STR "Information"
#define MSG_EXCHANGE_GAD_SHOW_STR "Show"
#define MSG_EXCHANGE_GAD_HIDE_STR "Hide"
#define MSG_EXCHANGE_GAD_REMOVE_STR "Remove"
#define MSG_EXCHANGE_CYCLE_ACTIVE_STR "Active"
#define MSG_EXCHANGE_CYCLE_INACTIVE_STR "Inactive"
#define MSG_BLANKER_CXNAME_STR "Blanker"
#define MSG_BLANKER_CXTITLE_STR "System Screen Blanker"
#define MSG_BLANKER_CXDESCR_STR "Blanks screen when system inactive"
#define MSG_CLICK2FNT_CXNAME_STR "ClickToFront"
#define MSG_CLICK2FNT_CXTITLE_STR "Click To Front Utility"
#define MSG_CLICK2FNT_CXDESCR_STR "Click windows to front"
#define MSG_OPAQUE_CXNAME_STR "Opaque"
#define MSG_OPAQUE_CXTITLE_STR "Solid Windows"
#define MSG_OPAQUE_CXDESCR_STR "Realtime moving of windows"
#define MSG_AUTOPOINT_CXNAME_STR "AutoPoint"
#define MSG_AUTOPOINT_CXTITLE_STR "Autopointer"
#define MSG_AUTOPOINT_CXDESCR_STR "Activates the window under the mouse"
#define MSG_STARTMENU_CXNAME_STR "StartMenu"
#define MSG_STARTMENU_CXTITLE_STR "System Program Starter"
#define MSG_STARTMENU_CXDESCR_STR "Program launch commodity"
#define MSG_FKEY_CXNAME_STR "FKey"
#define MSG_FKEY_CXTITLE_STR "Function To Keys:"
#define MSG_FKEY_CXDESCR_STR "Attach Special Functions To Keys"
#define MSG_FKEY_WINTITLE_STR "FKey: Hot Key = <%s>"
#define MSG_FKEY_DEFINED_KEYS_STR "Defined Keys"
#define MSG_FKEY_NEW_KEY_STR "_New Key"
#define MSG_FKEY_DELETE_KEY_STR "_Delete Key"
#define MSG_FKEY_COMMAND_STR "Command"
#define MSG_FKEY_COMMAND_PARAMS_STR "Command Parameters"
#define MSG_FKEY_CMD_CYCLE_WIN_STR "Cycle Windows"
#define MSG_FKEY_CMD_CYCLE_SCR_STR "Cycle Screens"
#define MSG_FKEY_CMD_ENLARGE_WIN_STR "Enlarge Window"
#define MSG_FKEY_CMD_SHRINK_WIN_STR "Shrink Window"
#define MSG_FKEY_CMD_TOGGLE_WIN_SIZE_STR "Toggle Window Size"
#define MSG_FKEY_CMD_INSERT_TEXT_STR "Insert Text"
#define MSG_FKEY_CMD_RUN_PROG_STR "Run Program"
#define MSG_FKEY_CMD_RUN_AREXX_STR "Run Arexx Script"
#define MSG_FKEY_MEN_PROJECT_STR "Project"
#define MSG_FKEY_MEN_PROJECT_SAVE_STR "S\000Save Defined Keys"
#define MSG_FKEY_MEN_PROJECT_HIDE_STR "H\000Hide"
#define MSG_FKEY_MEN_PROJECT_ICONIFY_STR "I\000Iconify"
#define MSG_FKEY_MEN_PROJECT_QUIT_STR "Q\000Quit"
#define MSG_NOCAPSLOCK_CXNAME_STR "NoCapsLock"
#define MSG_NOCAPSLOCK_CXTITLE_STR "NoCapsLock:"
#define MSG_NOCAPSLOCK_CXDESCR_STR "Renders the CAPS LOCK key ineffective"

#endif /* CATCOMP_STRINGS */


/***************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
  LONG   cca_ID;
  STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
  {MSG_CANT_OPEN_LIB,(STRPTR)MSG_CANT_OPEN_LIB_STR},
  {MSG_CANT_LOCK_SCR,(STRPTR)MSG_CANT_LOCK_SCR_STR},
  {MSG_CANT_GET_VI,(STRPTR)MSG_CANT_GET_VI_STR},
  {MSG_CANT_CREATE_GADGET,(STRPTR)MSG_CANT_CREATE_GADGET_STR},
  {MSG_CANT_CREATE_MENUS,(STRPTR)MSG_CANT_CREATE_MENUS_STR},
  {MSG_CANT_LAYOUT_MENUS,(STRPTR)MSG_CANT_LAYOUT_MENUS_STR},
  {MSG_CANT_CREATE_WIN,(STRPTR)MSG_CANT_CREATE_WIN_STR},
  {MSG_CANT_ALLOCATE_MEM,(STRPTR)MSG_CANT_ALLOCATE_MEM_STR},
  {MSG_CANT_CREATE_MSGPORT,(STRPTR)MSG_CANT_CREATE_MSGPORT_STR},
  {MSG_CANT_CREATE_BROKER,(STRPTR)MSG_CANT_CREATE_BROKER_STR},
  {MSG_CANT_CREATE_CUSTOM,(STRPTR)MSG_CANT_CREATE_CUSTOM_STR},
  {MSG_OK,(STRPTR)MSG_OK_STR},
  {MSG_MEN_PROJECT,(STRPTR)MSG_MEN_PROJECT_STR},
  {MSG_MEN_PROJECT_QUIT,(STRPTR)MSG_MEN_PROJECT_QUIT_STR},
  {MSG_EXCHANGE_CXNAME,(STRPTR)MSG_EXCHANGE_CXNAME_STR},
  {MSG_EXCHANGE_CXTITLE,(STRPTR)MSG_EXCHANGE_CXTITLE_STR},
  {MSG_EXCHANGE_CXDESCR,(STRPTR)MSG_EXCHANGE_CXDESCR_STR},
  {MSG_EXCHANGE_WINTITLE,(STRPTR)MSG_EXCHANGE_WINTITLE_STR},
  {MSG_EXCHANGE_LISTVIEW,(STRPTR)MSG_EXCHANGE_LISTVIEW_STR},
  {MSG_EXCHANGE_INFO,(STRPTR)MSG_EXCHANGE_INFO_STR},
  {MSG_EXCHANGE_GAD_SHOW,(STRPTR)MSG_EXCHANGE_GAD_SHOW_STR},
  {MSG_EXCHANGE_GAD_HIDE,(STRPTR)MSG_EXCHANGE_GAD_HIDE_STR},
  {MSG_EXCHANGE_GAD_REMOVE,(STRPTR)MSG_EXCHANGE_GAD_REMOVE_STR},
  {MSG_EXCHANGE_CYCLE_ACTIVE,(STRPTR)MSG_EXCHANGE_CYCLE_ACTIVE_STR},
  {MSG_EXCHANGE_CYCLE_INACTIVE,(STRPTR)MSG_EXCHANGE_CYCLE_INACTIVE_STR},
  {MSG_BLANKER_CXNAME,(STRPTR)MSG_BLANKER_CXNAME_STR},
  {MSG_BLANKER_CXTITLE,(STRPTR)MSG_BLANKER_CXTITLE_STR},
  {MSG_BLANKER_CXDESCR,(STRPTR)MSG_BLANKER_CXDESCR_STR},
  {MSG_CLICK2FNT_CXNAME,(STRPTR)MSG_CLICK2FNT_CXNAME_STR},
  {MSG_CLICK2FNT_CXTITLE,(STRPTR)MSG_CLICK2FNT_CXTITLE_STR},
  {MSG_CLICK2FNT_CXDESCR,(STRPTR)MSG_CLICK2FNT_CXDESCR_STR},
  {MSG_OPAQUE_CXNAME,(STRPTR)MSG_OPAQUE_CXNAME_STR},
  {MSG_OPAQUE_CXTITLE,(STRPTR)MSG_OPAQUE_CXTITLE_STR},
  {MSG_OPAQUE_CXDESCR,(STRPTR)MSG_OPAQUE_CXDESCR_STR},
  {MSG_AUTOPOINT_CXNAME,(STRPTR)MSG_AUTOPOINT_CXNAME_STR},
  {MSG_AUTOPOINT_CXTITLE,(STRPTR)MSG_AUTOPOINT_CXTITLE_STR},
  {MSG_AUTOPOINT_CXDESCR,(STRPTR)MSG_AUTOPOINT_CXDESCR_STR},
  {MSG_STARTMENU_CXNAME,(STRPTR)MSG_STARTMENU_CXNAME_STR},
  {MSG_STARTMENU_CXTITLE,(STRPTR)MSG_STARTMENU_CXTITLE_STR},
  {MSG_STARTMENU_CXDESCR,(STRPTR)MSG_STARTMENU_CXDESCR_STR},
  {MSG_FKEY_CXNAME,(STRPTR)MSG_FKEY_CXNAME_STR},
  {MSG_FKEY_CXTITLE,(STRPTR)MSG_FKEY_CXTITLE_STR},
  {MSG_FKEY_CXDESCR,(STRPTR)MSG_FKEY_CXDESCR_STR},
  {MSG_FKEY_WINTITLE,(STRPTR)MSG_FKEY_WINTITLE_STR},
  {MSG_FKEY_DEFINED_KEYS,(STRPTR)MSG_FKEY_DEFINED_KEYS_STR},
  {MSG_FKEY_NEW_KEY,(STRPTR)MSG_FKEY_NEW_KEY_STR},
  {MSG_FKEY_DELETE_KEY,(STRPTR)MSG_FKEY_DELETE_KEY_STR},
  {MSG_FKEY_COMMAND,(STRPTR)MSG_FKEY_COMMAND_STR},
  {MSG_FKEY_COMMAND_PARAMS,(STRPTR)MSG_FKEY_COMMAND_PARAMS_STR},
  {MSG_FKEY_CMD_CYCLE_WIN,(STRPTR)MSG_FKEY_CMD_CYCLE_WIN_STR},
  {MSG_FKEY_CMD_CYCLE_SCR,(STRPTR)MSG_FKEY_CMD_CYCLE_SCR_STR},
  {MSG_FKEY_CMD_ENLARGE_WIN,(STRPTR)MSG_FKEY_CMD_ENLARGE_WIN_STR},
  {MSG_FKEY_CMD_SHRINK_WIN,(STRPTR)MSG_FKEY_CMD_SHRINK_WIN_STR},
  {MSG_FKEY_CMD_TOGGLE_WIN_SIZE,(STRPTR)MSG_FKEY_CMD_TOGGLE_WIN_SIZE_STR},
  {MSG_FKEY_CMD_INSERT_TEXT,(STRPTR)MSG_FKEY_CMD_INSERT_TEXT_STR},
  {MSG_FKEY_CMD_RUN_PROG,(STRPTR)MSG_FKEY_CMD_RUN_PROG_STR},
  {MSG_FKEY_CMD_RUN_AREXX,(STRPTR)MSG_FKEY_CMD_RUN_AREXX_STR},
  {MSG_FKEY_MEN_PROJECT,(STRPTR)MSG_FKEY_MEN_PROJECT_STR},
  {MSG_FKEY_MEN_PROJECT_SAVE,(STRPTR)MSG_FKEY_MEN_PROJECT_SAVE_STR},
  {MSG_FKEY_MEN_PROJECT_HIDE,(STRPTR)MSG_FKEY_MEN_PROJECT_HIDE_STR},
  {MSG_FKEY_MEN_PROJECT_ICONIFY,(STRPTR)MSG_FKEY_MEN_PROJECT_ICONIFY_STR},
  {MSG_FKEY_MEN_PROJECT_QUIT,(STRPTR)MSG_FKEY_MEN_PROJECT_QUIT_STR},
  {MSG_NOCAPSLOCK_CXNAME,(STRPTR)MSG_NOCAPSLOCK_CXNAME_STR},
  {MSG_NOCAPSLOCK_CXTITLE,(STRPTR)MSG_NOCAPSLOCK_CXTITLE_STR},
  {MSG_NOCAPSLOCK_CXDESCR,(STRPTR)MSG_NOCAPSLOCK_CXDESCR_STR},
  {0,NULL}
};

#endif /* CATCOMP_ARRAY */

/***************************************************************/


#ifdef CATCOMP_BLOCK

//static const chat CatCompBlock[] =
//{
//     
//};

#endif /* CATCOMP_BLOCK */

/***************************************************************/

struct LocaleInfo
{
  APTR li_LocaleBase;
  APTR li_Catalog;
};


#ifdef CATCOMP_CODE

STRPTR GetString(struct LocaleInfo *li, LONG stringNum)
{
  LONG *l;
  UWORD *w;
  STRPTR  builtIn;

  l = (LONG *)CatCompBlock;

  while (*l != stringNum)
  {
    w = (UWORD *)((ULONG)l + 4);
    l = (LONG *)((ULONG)l + (LONG)*w + 6);
  }
  builtIn = (STRPTR)((ULONG)l + 6);

#define XLocaleBase LocaleBase
#define LocaleBase li->li_LocaleBase

  if (LocaleBase)
    return(GetCatalogStr(li->li_Catalog,stringNum,builtIn));
#define LocaleBase XLocaleBase
#undef XLocaleBase

  return (builtIn);
}  

#endif /* CATCOMP_CODE */

/***************************************************************/


#endif
